---
title: Irving Street Functionality
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
description: This is supposed to be a blog.
permalink: pretty
side_bar:
  posts:
    vw_threshold: 1000
    quantity: 5
  uploads:
    vw_threshold: 1000
    quantity: 5
site_colors:
  primary_background: "#20343b"
  light_background: "#32515c"
  dark_background: "#17252a"
  primary_font: "#ffffff"
  secondary_font: "#e9f9c9"
  tertiary_font: "#f2fce0"
contact_email: withheld@for.now
